--------------------------------------------------
-- Mir AI configuration file (generated by Mir AI Control Panel)
--------------------------------------------------
CIRCLE_ON_IDLE=1
FOLLOW_AT_ONCE=0
HELP_OWNER_1ST=false
KILL_YOUR_ENEMIES_1ST=true
LONG_RANGE_SHOOTER=false
BOLTS_ON_CHASE_ST=true
HP_PERC_DANGER=20
HP_PERC_SAFE2ATK=40
OWNER_CLOSEDISTANCE=2
TOO_FAR_TARGET=14
SKILL_TIME_OUT=2000
NO_MOVING_TARGETS=false
ADV_MOTION_CHECK=false
 

AAP = {}
AAP.Mode=3
AAP.HP_Perc=70
AAP.Level=4
 
--------------------------------------------------
-- Homunculus Skills: minimun SP to activate
--------------------------------------------------
-- Amistr
AS_AMI_BULW = {}
AS_AMI_BULW.MinSP=40
AS_AMI_BULW.Level=5
AS_AMI_CAST = {}
AS_AMI_CAST.MinSP=10
AS_AMI_CAST.Level=0
-- Filir
AS_FIL_MOON = {}
AS_FIL_MOON.MinSP=20
AS_FIL_MOON.Level=5
AS_FIL_ACCL = {}
AS_FIL_ACCL.MinSP=70
AS_FIL_ACCL.Level=0
AS_FIL_FLTT = {}
AS_FIL_FLTT.MinSP=70
AS_FIL_FLTT.Level=5
-- Lif
AS_LIF_HEAL = {}
AS_LIF_HEAL.MinSP=40
AS_LIF_HEAL.Level=5
AS_LIF_ESCP = {}
AS_LIF_ESCP.MinSP=40
AS_LIF_ESCP.Level=5
-- Vanilmirth
AS_VAN_CAPR = {}
AS_VAN_CAPR.MinSP=30
AS_VAN_CAPR.Level=5
AS_VAN_BLES = {}
AS_VAN_BLES.MinSP=40
AS_VAN_BLES.Level=0
 
--------------------------------------------------
-- Tact list: behaviour for each monster
--------------------------------------------------
DEFAULT_BEHA = BEHA_attack
DEFAULT_WITH = WITH_one_skill
Tact = {}
-- Ant hell 01
Tact[1097] = {"Ant Egg", BEHA_attack, WITH_one_skill, 5, 0}
Tact[1095] = {"Andre", BEHA_react, WITH_one_skill, 5, 0}
Tact[1160] = {"Pierre", BEHA_react, WITH_one_skill, 5, 0}
Tact[1105] = {"Deniro", BEHA_react, WITH_one_skill, 5, 0}
Tact[1176] = {"Vitata", BEHA_react, WITH_one_skill, 5, 0}
Tact[1121] = {"Giearth", BEHA_react, WITH_one_skill, 5, 0}
-- Moskovia 01
Tact[1880] = {"Wood Goblin", BEHA_react, WITH_one_skill, 5, 0}
Tact[1261] = {"Wild Rose", BEHA_react, WITH_full_power, 5, 0}
-- Orc Dungeon (lvl 50+ Settings)
Tact[1189] = {"Orc Archer", BEHA_react_1st, WITH_full_power, 5, 0}
Tact[1177] = {"Zenorc", BEHA_attack_1st, WITH_full_power, 5, 0}
Tact[1152] = {"Orc Skeleton", BEHA_react, WITH_one_skill, 5, 0}
Tact[1111] = {"Drainliar", BEHA_attack_weak, WITH_no_skill, 1, 0}
Tact[1042] = {"Steel Chonchon", BEHA_attack_last, WITH_one_skill, 1, 0}
-- Poring and Metaling fields
Tact[1368] = {"Geographer", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1118] = {"Flora", BEHA_coward, WITH_full_power, 5, 0}
Tact[1613] = {"Metaling", BEHA_react, WITH_one_skill, 5, 0}
Tact[1031] = {"Poporing", BEHA_react, WITH_one_skill, 5, 0}
Tact[1242] = {"Marin", BEHA_react, WITH_no_skill, 5, 0}
Tact[1113] = {"Drops", BEHA_attack, WITH_no_skill, 5, -1}
Tact[1002] = {"Poring", BEHA_attack_last, WITH_no_skill, 5, -1}
-- Summoned Plants
Tact[1555] = {"Sm. Parasite", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1575] = {"Sm. Flora", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1579] = {"Sm. Hydra", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1589] = {"Sm. Mandragora", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1590] = {"Sm. Geographer", BEHA_avoid, WITH_no_skill, 5, 0}
-- WoE Guardians
Tact[1285] = {"WoE Guardian 1", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1286] = {"WoE Guardian 2", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1287] = {"WoE Guardian 3", BEHA_avoid, WITH_no_skill, 5, 0}
Tact[1288] = {"WoE Guardian 4", BEHA_avoid, WITH_no_skill, 5, 0}
-- Plants and mushrooms
Tact[1078] = {"Red Plant", BEHA_react, WITH_no_skill, 5, 0}
Tact[1079] = {"Blue Plant", BEHA_react, WITH_no_skill, 5, 0}
Tact[1080] = {"Green Plant", BEHA_react, WITH_no_skill, 5, 0}
Tact[1081] = {"Yellow Plant", BEHA_react, WITH_no_skill, 5, 0}
Tact[1082] = {"White Plant", BEHA_react, WITH_no_skill, 5, 0}
Tact[1083] = {"Shining Plant", BEHA_react, WITH_no_skill, 5, 0}
Tact[1084] = {"Black Mushroom", BEHA_react, WITH_no_skill, 5, 0}
Tact[1085] = {"Red Mushroom", BEHA_react, WITH_no_skill, 5, 0}
-- End Tact